Fix getStaticProps/getServerSideProps callback type
Problem 1:
Invalid TS type that forces user to provide invalid data from callback function.

Currently, the code below is correct for TS:
```
export const getStaticProps = wrapper.getStaticProps<{ test: string }>(({ store, preview }) => {
  return {
    test: 'ser',
  };
});
```
but calling it will generate a NextJS error:
```
Server Error
Error: Additional keys were returned from `getStaticProps`. Properties intended for your component must be nested under the `props` key, e.g.:

	return { props: { title: 'My Title', content: '...' } }

Keys that need to be moved: test.
Read more: https://err.sh/next.js/invalid-getstaticprops-value
```

The correct version should be:
```
export const getStaticProps = wrapper.getStaticProps<{ test: string }>(({ store, preview }) => {
  return {
    props: {
      test: 'ser',
    },
  };
});
```
but this gives TS error:
```
Error:(96, 72) TS2345: Argument of type '({ store, preview }: GetStaticPropsContext & { store: Store<RootStore, AnyAction>; }) => { props: { test: string; }; }' is not assignable to parameter of type '(context: GetStaticPropsContext & { store: Store<RootStore, AnyAction>; }) => void | { test: string; }'.
  Type '{ props: { test: string; }; }' is not assignable to type 'void | { test: string; }'.
    Property 'test' is missing in type '{ props: { test: string; }; }' but required in type '{ test: string; }'.
```
---
Problem 2:
Callback doesn't allow returning data from async function

Currently the following example fails typecheck:
```
export const getStaticProps = wrapper.getStaticProps<{ test: string }>(
  async ({ store, preview }) => {
    const data = await getData();
    store.dispatch(SOME_ACTION(data));
    return {
      props: {
        test: data.id,
      },
    };
  }
);
```

```
Error:(97, 3) TS2345: Argument of type '({ store, preview }: GetStaticPropsContext & { store: Store<RootStore, AnyAction>; }) => Promise<{ props: { test: any; }; }>' is not assignable to parameter of type '(context: GetStaticPropsContext & { store: Store<RootStore, AnyAction>; }) => void | { test: string; }'.
  Type 'Promise<{ props: { test: any; }; }>' is not assignable to type 'void | { test: string; }'.
    Property 'test' is missing in type 'Promise<{ props: { test: any; }; }>' but required in type '{ test: string; }'.
```